<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="1" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="13596" started-at="2019-06-16T19:09:51Z" finished-at="2019-06-16T19:10:05Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="13596" started-at="2019-06-16T19:09:51Z" finished-at="2019-06-16T19:10:05Z">
      <class name="testcasestestng.SuccessFulLogin">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:testcasestestng.SuccessFulLogin@4c70fda8]" name="beforeSuite" is-config="true" duration-ms="10" started-at="2019-06-16T19:09:51Z" finished-at="2019-06-16T19:09:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:testcasestestng.SuccessFulLogin@4c70fda8]" name="beforeTest" is-config="true" duration-ms="0" started-at="2019-06-16T19:09:51Z" finished-at="2019-06-16T19:09:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:testcasestestng.SuccessFulLogin@4c70fda8]" name="beforeClass" is-config="true" duration-ms="0" started-at="2019-06-16T19:09:51Z" finished-at="2019-06-16T19:09:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:testcasestestng.SuccessFulLogin@4c70fda8]" name="beforeMethod" is-config="true" duration-ms="5279" started-at="2019-06-16T19:09:51Z" finished-at="2019-06-16T19:09:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="testThree()[pri:2, instance:testcasestestng.SuccessFulLogin@4c70fda8]" name="testThree" duration-ms="53" started-at="2019-06-16T19:09:57Z" description="Welcome message" finished-at="2019-06-16T19:09:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testThree -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:testcasestestng.SuccessFulLogin@4c70fda8]" name="afterMethod" is-config="true" duration-ms="675" started-at="2019-06-16T19:09:57Z" finished-at="2019-06-16T19:09:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:testcasestestng.SuccessFulLogin@4c70fda8]" name="beforeMethod" is-config="true" duration-ms="4168" started-at="2019-06-16T19:09:57Z" finished-at="2019-06-16T19:10:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="testOne_SuccessfulLogin()[pri:3, instance:testcasestestng.SuccessFulLogin@4c70fda8]" name="testOne_SuccessfulLogin" duration-ms="2705" started-at="2019-06-16T19:10:01Z" description="Successful login" finished-at="2019-06-16T19:10:04Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at testcasestestng.SuccessFulLogin.testOne_SuccessfulLogin(SuccessFulLogin.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testOne_SuccessfulLogin -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:testcasestestng.SuccessFulLogin@4c70fda8]" name="afterMethod" is-config="true" duration-ms="688" started-at="2019-06-16T19:10:04Z" finished-at="2019-06-16T19:10:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:testcasestestng.SuccessFulLogin@4c70fda8]" name="afterClass" is-config="true" duration-ms="1" started-at="2019-06-16T19:10:05Z" finished-at="2019-06-16T19:10:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:testcasestestng.SuccessFulLogin@4c70fda8]" name="afterTest" is-config="true" duration-ms="0" started-at="2019-06-16T19:10:05Z" finished-at="2019-06-16T19:10:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:testcasestestng.SuccessFulLogin@4c70fda8]" name="afterSuite" is-config="true" duration-ms="0" started-at="2019-06-16T19:10:05Z" finished-at="2019-06-16T19:10:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- testcasestestng.SuccessFulLogin -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
